lab:
  description: ''
  notes: ''
  timestamp: 1619699117.7692037
  title: voornaam.familienaam-PROD   ############ Aanpassen !!! ###########
  version: 0.0.4
nodes:
  - id: n0
    label: ext-conn-0
    node_definition: external_connector
    x: -550
    y: -50
    configuration: bridge41
    tags: []
    interfaces:
      - id: i0
        slot: 0
        label: port
        type: physical
  - id: n1
    label: unmanaged-switch-0
    node_definition: unmanaged_switch
    x: -350
    y: -50
    configuration: ''
    tags: []
    interfaces:
      - id: i0
        slot: 0
        label: port0
        type: physical
      - id: i1
        slot: 1
        label: port1
        type: physical
      - id: i2
        slot: 2
        label: port2
        type: physical
      - id: i3
        slot: 3
        label: port3
        type: physical
      - id: i4
        slot: 4
        label: port4
        type: physical
      - id: i5
        slot: 5
        label: port5
        type: physical
      - id: i6
        slot: 6
        label: port6
        type: physical
      - id: i7
        slot: 7
        label: port7
        type: physical
  - id: n2
    label: border-router
    node_definition: iosv
    x: -200
    y: -50
    configuration: |-
      ! IOS Config generated on 2021-04-29 09:36
      ! by ank-ng
      !
      hostname border-router
      boot-start-marker
      boot-end-marker
      !
      !
      no aaa new-model
      !
      !
      service timestamps debug datetime msec
      service timestamps log datetime msec
      no service password-encryption
      no service config
      enable password cisco
      enable secret 4 tnhtc92DXBhelxjYk8LWJrPV36S2i4ntXrpb4RFmfqY
      ip classless
      ip subnet-zero
      no ip domain lookup
      ip domain name virl.info
      crypto key generate rsa modulus 768
      ip ssh server algorithm authentication password
      username cisco privilege 15 secret cisco
      line vty 0 4
       transport input ssh telnet
       exec-timeout 720 0
       password cisco
       login local
      line con 0
       password cisco
      !
      no cdp run
      !
      !
      interface Loopback0
          description to
          no ip address
          shutdown
      interface GigabitEthernet0/0
          description to port1.unmanaged-switch-0
      ! #################################### ip adres hieronder aanpassen ##################################
          ip address y.y.y.y 255.255.255.0
          no shutdown
      interface GigabitEthernet0/1
          description to GigabitEthernet0/0.internal-router
          no ip address
          no shutdown
      interface GigabitEthernet0/2
          description to
          no ip address
          shutdown
      interface GigabitEthernet0/3
          description to
          no ip address
          shutdown

      ip route 0.0.0.0 0.0.0.0 10.129.41.254
      !
      end
    image_definition: iosv-158-3
    tags: []
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        slot: 0
        label: GigabitEthernet0/0
        type: physical
      - id: i2
        slot: 1
        label: GigabitEthernet0/1
        type: physical
      - id: i3
        slot: 2
        label: GigabitEthernet0/2
        type: physical
      - id: i4
        slot: 3
        label: GigabitEthernet0/3
        type: physical
  - id: n3
    label: internal-router
    node_definition: iosv
    x: -250
    y: -200
    configuration: |-
      ! IOS Config generated on 2021-04-29 09:36
      ! by ank-ng
      !
      hostname internal-router
      boot-start-marker
      boot-end-marker
      !
      !
      no aaa new-model
      !
      !
      service timestamps debug datetime msec
      service timestamps log datetime msec
      no service password-encryption
      no service config
      enable password cisco
      enable secret 4 tnhtc92DXBhelxjYk8LWJrPV36S2i4ntXrpb4RFmfqY
      ip classless
      ip subnet-zero
      no ip domain lookup
      ip domain name virl.info
      crypto key generate rsa modulus 768
      ip ssh server algorithm authentication password
      username cisco privilege 15 secret cisco
      line vty 0 4
       transport input ssh telnet
       exec-timeout 720 0
       password cisco
       login local
      line con 0
       password cisco
      !
      no cdp run
      !
      !
      interface Loopback0
          description to
          no ip address
          shutdown
      interface GigabitEthernet0/0
          description to GigabitEthernet0/1.border-router
          ip address 192.168.1.2 255.255.255.0
          no shutdown
      interface GigabitEthernet0/1
          description to
          no ip address
          shutdown
      interface GigabitEthernet0/2
          description to
          no ip address
          shutdown
      interface GigabitEthernet0/3
          description to
          no ip address
          shutdown
      !
      !
      end
    image_definition: iosv-158-3
    tags: []
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        slot: 0
        label: GigabitEthernet0/0
        type: physical
      - id: i2
        slot: 1
        label: GigabitEthernet0/1
        type: physical
      - id: i3
        slot: 2
        label: GigabitEthernet0/2
        type: physical
      - id: i4
        slot: 3
        label: GigabitEthernet0/3
        type: physical
links:
  - id: l0
    i1: i0
    n1: n0
    i2: i0
    n2: n1
  - id: l1
    i1: i1
    n1: n1
    i2: i1
    n2: n2
  - id: l2
    i1: i2
    n1: n2
    i2: i1
    n2: n3
