---
- name: Play die volledige routerconfig naar production lab importeert
  hosts: production 
  gather_facts: no
  
  tasks:
    - name: config importeren in de router
      cisco.ios.ios_config:
        src: backup/running-config.cfg      

    - name: save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified


  

