---
- name: Play die routerconfig aanpast bij development lab
  hosts: development
  gather_facts: no
  tasks:
    - name: Configure IP 192.168.1.1/24 on G0/1
      cisco.ios.ios_config:
       lines:
       - ip address 192.168.1.1 255.255.255.0
       parents: interface G0/1
    - name: Add 2 loopback interfaces with IP 172.16.29.1-2 /24
      cisco.ios.ios_config:
       lines:
       - ip address {{ item.ip }} 255.255.255.0
       parents: interface {{ item.name }}
      with_items:
      - {name: loopback1, ip: 172.16.29.1}
      - {name: loopback2, ip: 172.17.29.1}

    - name: Test reachability tussen routers
      cisco.ios.ios_ping:
        dest: 192.168.1.2
      register: info

    - name: Output selected info
      debug:
        msg: 
          - "Het command {{ info.commands }} was succesvol"
          - "Packet loss: {{ info.packet_loss }}"
          - "Round Trip Time: {{ info.rtt }}"

    - name: Backup running_config
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: running-config.cfg
          dir_path: ansible/backup/


  

